### ISSUE TITLE
要如何執行

### ISSUE THREAD

**Issue by EastL** [Yi-Tseng/FBChatRank#1]
請問是執行app.js嗎?執行後出現錯誤....
Error: Most middleware (like favicon) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (/home/eric/document/FBChatRank/node_modules/express/lib/express.js:99:13)
    at Object.<anonymous> (/home/eric/document/FBChatRank/app.js:15:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

**Comment by EastL** [comment]
安裝了serve-favicon也是出現這個錯誤
